version: '3.1'
networks:
  - btcpal_default:
      driver: bridge

services:

  web:
    build: .
    networks:
      - btcpal_default
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/admin

    ports:
    - 4321:4321





#
#  mongo-express:
#    image: mongo-express
#    restart: unless-stopped
#    depends_on:
#      - mongodb
#    links:
#      - mongodb
#    ports:
#    - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: user
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
