version: '3.1'
services:
  db:
    image: mongo
    env_file:
    - .env
    container_name: db
    ports:
    - "27017:27017"
    restart: unless-stopped
#    volumes:
#    - ./data/db:/data/db
    networks:
    - default
    - btcstore
  web:
    container_name: webapp
    build: .
    depends_on:
    - db
    restart: unless-stopped
    networks:
    - default
    - btcstore
    env_file:
    - .env
    ports:
    - "${APP_PORT}:${APP_PORT}"
networks:
  btcstore:
    driver: bridge
