version: '3.1'
services:
  ttt:
    build: .
    external_links:
      - db
    restart: always
    networks:
    - generated_default
    env_file:
    - .env
    ports:
    - "${APP_PORT}:${APP_PORT}"
networks:
  tic_tac_toe:
  generated_default:
    external:
      name: generated_default
