version: '3.1'

services:

  web:
    build: .
    restart: unless-stopped
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://${MONGO_DB_USERNAME}:${MONGO_DB_PASSWORD}@mongodb:27017/admin
    networks:
    - btcpal_default:
        external: true
    ports:
    - 4321:4321

#
#  mongo-express:
#    image: mongo-express
#    restart: unless-stopped
#    depends_on:
#      - mongodb
#    links:
#      - mongodb
#    ports:
#    - 8081:8081
#    environment:
#      ME_CONFIG_MONGODB_ADMINUSERNAME: user
#      ME_CONFIG_MONGODB_ADMINPASSWORD: example
