version: '3.1'
services:
  db:
    image: mongo
    env_file:
    - .env
    container_name: db
    ports:
    - "27017:27017"
    restart: unless-stopped
    networks:
      - lndstore
    #    volumes:
    #    - ./data/db:/data/db
  web:
    container_name: webapp
    build: .
    depends_on:
    - db
    restart: unless-stopped
    networks:
    - ${BTCPAY_NETWORK}
    - lndstore
    env_file:
    - .env
    ports:
    - "${APP_PORT}:${APP_PORT}"
networks:
  lndstore:
  [${BTCPAY_NETWORK}]:
    external:
      name: generated_default
