version: '3.1'
services:
  ttt:
    build: .
    external_links:
      - db
    restart: always
    networks:
    - generated_default
    - lightning-api-purchase_lndstore
    env_file:
    - .env
    ports:
    - "${APP_PORT}:${APP_PORT}"
networks:
  lightning-api-purchase_lndstore:
    external:
      name: lightning-api-purchase_lndstore
  generated_default:
    external:
      name: generated_default
