version: '3.1'
services:
  db:
    image: mongo
    env_file:
    - .env
    #container_name: db
    ports:
    - "27017:27017"
    restart: unless-stopped
      #    volumes:
      #    - ./data/db:/data/db
      networks:
      - btcstore
      # - generated_default
  web:
    container_name: webapp
    build: .
    depends_on:
    - db
    restart: unless-stopped
    networks:
    - btcstore
    - generated_default
    env_file:
    - .env
    ports:
    - "${APP_PORT}:${APP_PORT}"
networks:
  generated_default:
    external:
      name: generated_default
#  btcstore:
#    driver: bridge
