version: '3.1'

services:

  mongodb:
    networks:
      - btcpal_default
    image: mongo
    ports:
      - 27017:27017
  web:
    links:
      - mongodb:mongo
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
    - 4321:4321
